### ISSUE TITLE
陪练注册

### ISSUE THREAD

**Issue by Akagilnc** [Akagilnc/momo-web#1]
陪练 可以通过微信公众号的自定义菜单，或者网页地址， **填写资料** 进行注册，注册成功后进入 **等待管理员审核** 状态，此状态一切功能可用，但是学员 **无法搜索到此陪练**

**Comment by Akagilnc** [comment]
字段：
username（pk）
avatar (image)
phone（国家区号+号码）
First Name
Last Name
intro
favorite topic
age
sex
country

**Comment by TechQuery** [comment]
948372a
