### ISSUE TITLE
陪练设定练习时间与人数上限

### ISSUE THREAD

**Issue by Akagilnc** [Akagilnc/momo-web#2]
**审批通过** 的陪练登陆后， 可以在 **个人中心** 设定 **每周** 的 **练习时间** 与每个练习时间可参与学生的 **人数上限**  例如（周日晚上 18:00 - 19:00，4人）。 让学员可以根据自己的需要选择

**Comment by Akagilnc** [comment]
目前的可以 **订课的时间段** ：

周六 / 早上7:30-8:30

周六 / 早上8:40-9:40

周六 / 晚上7:30-8:30

周六 / 晚上8:40-9:40

周日 / 早上7:30-8:30

周日 / 早上8:40-9:40

周日 / 晚上7:30-8:30

周日 / 晚上8:40-9:40

**Comment by TechQuery** [comment]
be2aaaa
